CREATE TABLE IF NOT EXISTS urls (
    id BIGSERIAL PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    original_url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_urls_code ON urls(code);

GRANT ALL PRIVILEGES ON TABLE urls TO shortener_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO shortener_user;